version: "3.3"
services:
  web:
    image: stevenfollis/visualizeer:latest
    ports:
      - "80:80"
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker
      labels:
        com.docker.lb.hosts: viz.apps.moby.com
        com.docker.lb.network: visualizeer_default
        com.docker.lb.port: 80
        com.docker.lb.websocket_endpoints: /
    secrets:
      - visualizeer.ucp_fqdn
      - visualizeer.ucp_username
      - visualizeer.ucp_password

secrets:
  visualizeer.ucp_fqdn:
    external: true
  visualizeer.ucp_username:
    external: true
  visualizeer.ucp_password:
    external: true