version: "3.3"
services:
  web:
    image: stevenfollis/visualizeer:latest
    ports:
      - "80"
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker
    secrets:
      - visualizeer.ucp_fqdn
      - visualizeer.ucp_username
      - visualizeer.ucp_password

secrets:
  visualizeer.ucp_fqdn:
    external: true
  visualizeer.ucp_username:
    external: true
  visualizeer.ucp_password:
    external: true